project:
  type: website

website:
  title: "Economic Losses Vs. Climate Score"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: bar-chart.qmd
        text: Plot 1
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



