project:
  type: website

website:
  title: "Economic Losses Vs. Climate Score"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Plots
        menu:
          - href: bar-chart.qmd
            text: Plot 1
      - href: sources.qmd
        text: Sources
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



